//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIPusingWPFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drug
    {
        public string PrescriptionId { get; set; }
        public string DrugName { get; set; }
        public string TimeDuration { get; set; }
        public string TimesPerDay { get; set; }
        public string DosagePerTime { get; set; }
        public string Usage { get; set; }
        public string Instruction { get; set; }
        public string WhenMorning { get; set; }
        public string WhenAfternoon { get; set; }
        public string WhenEvening { get; set; }
    }
}
